### ISSUE TITLE
Can be marked as 1.19.3 compatible

### ISSUE THREAD

**Issue by sternschnaube** [pcal43/storage-bookshelves#3]
Hello, the server starts without any problems - I was not testing it in-game yet, but I assume everything works.
I would close it when I can make the final confirm 😊

**Comment by venaminecraft** [comment]
Hello @pcal43, I was now walking randomly around and pressed right blick to hold my shield.
Then the server crashed with this error log here:

Encountered an unexpected exception
java.lang.NoSuchFieldError: field_11146
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4) ~[?:?]
	at net.pcal.storage_bookshelves.ProxyBlockService.onUseBlock(ProxyBlockService.java:77) ~[storage-bookshelves-0.0.1+1.19.2.jar:?]
	at net.minecraft.block.AbstractBlock.handler$fbb000$_onUse(AbstractBlock:3034) ~[?:?]
	at net.minecraft.block.AbstractBlock.onUse(AbstractBlock) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:995) ~[?:?]
	at net.minecraft.server.network.ServerPlayerInteractionManager.redirect$zme000$activateWithOptionalCactus(ServerPlayerInteractionManager:1529) ~[?:?]
	at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:342) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1146) ~[?:?]
	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:34) ~[?:?]
	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
	at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:156) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:787) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:166) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:130) ~[?:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:769) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:763) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:139) ~[?:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:748) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zjg000$modifiedRunLoop(MinecraftServer:5917) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:655) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:264) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
